### ISSUE TITLE
翻车了

### ISSUE THREAD

**Issue by Jackpoint666** [tonquer/ehentai-windows#1]
![image](https://user-images.githubusercontent.com/37446190/131208192-99582040-0d7f-499d-a642-5598d0d3c2d1.png)
无法正常打开，没办法显示不同分流

**Comment by Jackpoint666** [comment]
![image](https://user-images.githubusercontent.com/37446190/131208228-e843add5-6bd1-49cb-87b3-b119d31a4c18.png)

**Comment by tonquer** [comment]
把目录下config.ini删除试试

**Comment by Jackpoint666** [comment]
第一次没有留下config可以运行，但跳过登录后解析出错（不知道是账号还是网络的锅）。关闭程序生成config后就会报错了

**Comment by tonquer** [comment]
是有bug，如果不输入账号点登录，就无法重新打开了

**Comment by tonquer** [comment]
已经修复了
