### ISSUE TITLE
ehentai-win10报错 bika-win10可以运行  

### ISSUE THREAD

**Issue by 2362918558** [tonquer/ehentai-windows#3]
Could not find QtWebEngineProcess.exe
![图片](https://user-images.githubusercontent.com/29142928/132968095-a9a0c501-e40d-4432-ab9e-aca582b7f428.png)

**Comment by 2362918558** [comment]
哔咔可以打开  eh直接退了

**Comment by 2362918558** [comment]
Could not find QtWebEngineprocess.exe  没中文路径出了这个

**Comment by tonquer** [comment]
界面无法正常显示吗

**Comment by 2362918558** [comment]
> 
> 
> 界面无法正常显示吗

直接闪退了
 1.0.0的没问题

**Comment by tonquer** [comment]
QtWebEngineProcess是一个内置浏览器，在本项目是用来登陆时出现Google验证，通关打开网页加载Google验证。
目前我试了几台电脑都没发现有这个提示。
我发布了一个新的版本ehentai_v1.0.3_windows_no_QtWebEngineProcess.zip
，https://github.com/tonquer/ehentai-windows/releases/tag/v1.0.3，去掉了QtWebEngineProcess这个依赖，
但是登陆出现Google验证的话，将无法用帐号登陆，只能用Cookie登陆。
你可以试试能不能打开了

**Comment by 2362918558** [comment]
> 
> 
> QtWebEngineProcess是一个内置浏览器，在本项目是用来登陆时出现Google验证，通关打开网页加载Google验证。
> 目前我试了几台电脑都没发现有这个提示。
> 我发布了一个新的版本ehentai_v1.0.3_windows_no_QtWebEngineProcess.zip，
> [https://github.com/tonquer/ehentai-windows/releases/tag/v1.0.3 ](https://github.com/tonquer/ehentai-windows/releases/tag/v1.0.3)
> 去掉了QtWebEngineProcess这个依赖，
> 但是登陆出现Google验证的话，将无法用帐号登陆，只能用Cookie登陆。
> 你可以试试能不能打开了

谢谢 问题已解决
